# Generated by Django 3.1.2 on 2020-10-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_gram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
